[toolchain]
channel = "nightly-2025-07-11"
components = ["rustfmt", "miri", "clippy", "rust-src", "llvm-tools"]
targets = ["wasm32-unknown-unknown", "riscv64gc-unknown-none-elf", "aarch64-unknown-none"]
profile = "minimal"
