[target.'cfg(all(target_arch = "riscv64", target_os="none"))']
runner = "just _runner"
rustflags = [
    "-C",
    "link-args=-zseparate-loadable-segments",
    "-C",
    "link-args=--image-base=0xffffffff80000000",
]
